/*
 * App.c
 *
 * Created: 13/09/2022 02:28:37 م
 *  Author: 3m
 */ 

#include "App.h"


void App_INIT()
{    
	//INITIALIZE ALL THE 6 LEDS
	LED_INIT(PORTA_ID,PIN0_ID);
	LED_INIT(PORTA_ID,PIN1_ID);
	LED_INIT(PORTA_ID,PIN2_ID);
	LED_INIT(PORTB_ID,PIN0_ID);
	LED_INIT(PORTB_ID,PIN1_ID);
	LED_INIT(PORTB_ID,PIN2_ID);
	
	LEDs_OFF();  //ALL LEDS ARE OFF AT THE BEGINNING
		
	Button_Init(PORTD_ID,PIN2_ID);   //INITALIZE PUSH BUTTON AS INPUT
	INT0_Init();    //INITIALIZE INTERRUPT TO DETECT RISING EDGE
	timer_init();    //INITIALIZE THE TIMER FOR NORMAL MODE

}

void App_start()
{
	//BOTH YELLOW LEDS ARE OFF
	    
		LED_ON(PORTA_ID,PIN0_ID);   //CARS GREEN LED ON
		LED_ON(PORTB_ID,PIN2_ID);   //PED. RED LED ON
		Timer0_Delay_5_sec();
		
		LED_OFF(PORTA_ID,PIN0_ID); //CARS GREEN LED OFF
		LED_OFF(PORTB_ID,PIN2_ID); //PED. RED LED OFF
		
		yellow_blink();   //BOTH YELLOW LEDS START TO BLINK FOR 5 SEC
		
		LED_ON(PORTA_ID,PIN2_ID); //CARS RED LED ON
		LED_ON(PORTB_ID,PIN0_ID);   //PED. GREEN LED ON
		Timer0_Delay_5_sec();
		
		LED_OFF(PORTA_ID,PIN2_ID);  //CARS RED LED OFF
		LED_OFF(PORTB_ID,PIN0_ID);  //PED. GREEN LED OFF
		
		yellow_blink();   // BOTH YELLOW LEDS START TO BLINK FOR 5 SEC
	
}
