/*
 * App.c
 *
 * Created: 13/09/2022 02:28:37 م
 *  Author: 3m
 */ 

#include "App.h"

ISR(INT0_vect)
{	
	
	if((GPIO_readPin(PORTA_ID,PIN0_ID)) || (GPIO_readPin(PORTA_ID,PIN1_ID)) )
	{
		LED_OFF(PORTA_ID,PIN0_ID);
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTA_ID,PIN2_ID);
		LED_OFF(PORTB_ID,PIN0_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN2_ID);
		
		LED_ON(PORTA_ID,PIN0_ID);
		LED_ON(PORTB_ID,PIN2_ID);
		Timer0_Delay_5_sec();
        LED_OFF(PORTA_ID,PIN0_ID);
		LED_OFF(PORTB_ID,PIN2_ID);
		
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		
		LED_ON(PORTA_ID,PIN2_ID);
		LED_ON(PORTB_ID,PIN0_ID);
		Timer0_Delay_5_sec();
		LED_OFF(PORTA_ID,PIN2_ID);
		
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTB_ID,PIN0_ID);
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		
		LED_ON(PORTB_ID,PIN2_ID);
		LED_ON(PORTA_ID,PIN0_ID);
		Timer0_Delay_5_sec();
		LED_OFF(PORTB_ID,PIN2_ID);
		LED_OFF(PORTA_ID,PIN0_ID);
		
		
	}
	else if(GPIO_readPin(PORTA_ID,PIN2_ID))   //check for cars red led on 
	{
		LED_OFF(PORTA_ID,PIN0_ID);
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTA_ID,PIN2_ID);
		LED_OFF(PORTB_ID,PIN0_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN2_ID);
		
		LED_ON(PORTA_ID,PIN2_ID);
		LED_ON(PORTB_ID,PIN0_ID);
		Timer0_Delay_5_sec();
		LED_OFF(PORTA_ID,PIN2_ID);
		
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTB_ID,PIN0_ID);
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		
		LED_ON(PORTB_ID,PIN2_ID);
		LED_ON(PORTA_ID,PIN0_ID);
		Timer0_Delay_5_sec();
		LED_OFF(PORTB_ID,PIN2_ID);
		LED_OFF(PORTA_ID,PIN0_ID);
		
	}
}

void App_INIT()
{
	LED_INIT(PORTA_ID,PIN0_ID);
	LED_INIT(PORTA_ID,PIN1_ID);
	LED_INIT(PORTA_ID,PIN2_ID);
	LED_INIT(PORTB_ID,PIN0_ID);
	LED_INIT(PORTB_ID,PIN1_ID);
	LED_INIT(PORTB_ID,PIN2_ID);
	
	LED_OFF(PORTA_ID,PIN0_ID);
	LED_OFF(PORTA_ID,PIN1_ID);
	LED_OFF(PORTA_ID,PIN2_ID);
	LED_OFF(PORTB_ID,PIN0_ID);
	LED_OFF(PORTB_ID,PIN1_ID);
	LED_OFF(PORTB_ID,PIN2_ID);
	
	Button_Init(PORTD_ID,PIN2_ID);
	INT0_Init();
	timer_init();

}

void App_start()
{
	
	    LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		LED_ON(PORTA_ID,PIN0_ID);
		LED_ON(PORTB_ID,PIN2_ID);
		Timer0_Delay_5_sec();
		
		LED_OFF(PORTA_ID,PIN0_ID);
		LED_OFF(PORTB_ID,PIN2_ID);
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
        	LED_ON(PORTA_ID,PIN1_ID);
        	LED_ON(PORTB_ID,PIN1_ID);
        	Timer0_Delay_1_sec();
        	LED_OFF(PORTA_ID,PIN1_ID);
        	LED_OFF(PORTB_ID,PIN1_ID);
        	Timer0_Delay_1_sec();
			LED_ON(PORTA_ID,PIN1_ID);
			LED_ON(PORTB_ID,PIN1_ID);
			Timer0_Delay_1_sec();

		
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		LED_ON(PORTA_ID,PIN2_ID);
		LED_ON(PORTB_ID,PIN0_ID);
		Timer0_Delay_5_sec();
		
		LED_OFF(PORTA_ID,PIN2_ID);
		LED_OFF(PORTB_ID,PIN0_ID);
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_OFF(PORTA_ID,PIN1_ID);
		LED_OFF(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
		LED_ON(PORTA_ID,PIN1_ID);
		LED_ON(PORTB_ID,PIN1_ID);
		Timer0_Delay_1_sec();
	
}
